"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/views/layout/NavBar";
import SideBar from "@/components/views/layout/SideBar";
import { Toaster } from "@/components/ui/sonner";

import { useEffect } from "react";
import Database from "tauri-plugin-sql-api";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  async function insert(today) {
    try {
      const db = await Database.load('sqlite:data.db');
      const result = await db.execute("CREATE TABLE IF NOT EXISTS appconfig (id INTEGER PRIMARY KEY, start_date TEXT NOT NULL, theme TEXT NOT NULL)");
      const select = await db.select("SELECT COUNT(*) AS COUNT FROM appconfig");
      if (select[0].COUNT == 0) {
        const insert = await db.execute("INSERT OR REPLACE INTO appconfig (id, start_date, theme) VALUES (1, ?, ?)", [today, "light"]);
      }
    } catch (error) {
      console.log("error : ", error)
    }
  }

  useEffect(() => {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, "0");
    const day = String(now.getDate()).padStart(2, "0");

    const today = `${year}-${month}-${day}`;
    insert(today);
  }, []);

  return (
    <html lang="en">
      <body className="flex flex-col h-screen w-screen">
        <NavBar />
        <div className="flex flex-1 overflow-hidden">
          <SideBar />
          <main className={inter.className + " grow overflow-y-auto"}>
            {children}
          </main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
